const APPLY_FILTER_PRODUCT = 'Filter/APPLY_FILTER_PRODUCT';
const REMOVE_FILTER_PRODUCT = 'Filter/REMOVE_FILTER_PRODUCT';

export default {
    APPLY_FILTER_PRODUCT,
    REMOVE_FILTER_PRODUCT,
};
