const SHOW_SUCCESS_SNACKBAR = 'SnackBar/SHOW_SUCCESS_SNACKBAR';
const SHOW_ERROR_SNACKBAR = 'SnackBar/SHOW_ERROR_SNACKBAR';
const SNACKBAR_CLEAR = 'SnackBar/SNACKBAR_CLEAR';
const CLOSE_SUCCESS_SNACKBAR = 'SnackBar/CLOSE_SUCCESS_SNACKBAR';
const CLOSE_ERROR_SNACKBAR = 'SnackBar/CLOSE_ERROR_SNACKBAR';

export default {
    SHOW_SUCCESS_SNACKBAR,
    SHOW_ERROR_SNACKBAR,
    SNACKBAR_CLEAR,
    CLOSE_SUCCESS_SNACKBAR,
    CLOSE_ERROR_SNACKBAR
};
